security:
    password_hashers:
        # Utilisé pour hacher les mots de passe des utilisateurs
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: /

    access_control:
        # Autorise l'accès public aux routes d'inscription et de connexion
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

        # Empêche les utilisateurs non authentifiés d’accéder au reste du site
        - { path: ^/event/create, roles: ROLE_ORGANIZER }
        - { path: ^/events, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ORGANIZER: [ROLE_USER, ROLE_ORGANIZER]
        ROLE_ADMIN: [ROLE_ORGANIZER, ROLE_ADMIN, ROLE_USER]